config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :posts, param: :pid

  namespace :admin do
    resources :posts, param: :pid do
      post "toggle", on: :member
    end
    resources :tags, only: %w(index create destroy)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 50 }
  validates :content, presence: true
  validates :description, presence: true, length: { maximum: 200 }

  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  belongs_to :user

  scope :desc, -> { order(id: :desc) }
  scope :published, -> { where(published: true) }
  scope :count_per_month, -> { group("DATE_FORMAT(created_at, '%Y / %m')").count }

  before_create :create_pid
  before_update :changed_published_status

  def self.get_by_published_month(year, month)
    month_d = Date.new(year, month)

    where(published_at: month_d..month_d.end_of_month)
  end

  def self.posts_per_month
    Post.group("MONTH(date)")
  end

  private

  def changed_published_status
    if published_changed? && published_at.nil? && published?
      self.published_at = Time.zone.now
    end
  end

  def create_pid
    self.pid = SecureRandom.uuid
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags

  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :status, presence: true
  validates :password, presence: true, length: { minimum: 8 }, password: true
  validates :email, presence: true, uniqueness: true, email: true
  has_many :posts, dependent: :destroy

  enum status: %i(user admin)
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :redirect_root_without_admin

  private

  def redirect_root_without_admin
    redirect_to root_path unless admin_login?
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  def index
    @posts = Admin::PostDecorator.decorate_collection(Post.all.desc)
  end

  def show
    @post = current_user.posts.find_by(pid: params[:pid])&.decorate
    not_found if @post.nil?
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to admin_post_path(@post.pid)
    else
      render :new
    end
  end

  def edit
    @post = current_user.posts.find_by(pid: params[:pid])
    not_found if @post.nil?
  end

  def update
    @post = current_user.posts.find_by(pid: params[:pid])
    not_found if @post.nil?

    if @post.update(post_params)
      redirect_to admin_post_path(@post.pid)
    else
      render :edit
    end
  end

  def destroy
    @post = current_user.posts.find_by(pid: params[:pid])
    not_found if @post.nil?

    @post.destroy!
    redirect_to admin_posts_path
  end

  def toggle
    post = Post.find_by(pid: params[:pid])
    not_found if post.nil?

    post.toggle!(:published)
    redirect_to admin_posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :description, tag_ids: [])
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < Admin::BaseController
  def index
    @tags = Tag.all
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to admin_tags_path
    else
      @tags = Tag.all
      render :index
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to admin_tags_path
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  if Rails.env.production?
    rescue_from StandardError, with: :render_500
    rescue_from ActiveRecord::RecordNotFound, ActionController::RoutingError, with: :render_404
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  protected

  def not_found
    raise ActiveRecord::RecordNotFound
  end

  def admin_login?
    !!current_user&.admin?
  end

  def user_login?
    !!current_user&.user?
  end

  private

  def render_404
    render "errors/404"
  end

  def render_500
    render "errors/500"
  end

  helper_method :admin_login?
end

app/controllers/posts_controller.rb
class PostsController < UserPageController
  def index
    @posts = PostDecorator.decorate_collection(Post.published.desc.page(params[:page]).per(10))
  end

  def show
    @post = Post.published.find_by(pid: params[:pid])&.decorate
    not_found if @post.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_with_login, only: %i(new create)

  def new
  end

  def create
    @login = LoginService.new(login_params)
    if user = @login.call
      session[:user_id] = user.id
      redirect_to admin_posts_path and return
    end

    render :new
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end

  private

  def login_params
    params.permit(:email, :password)
  end

  def redirect_with_login
    redirect_to root_path if current_user.present?
  end
end

app/controllers/user_page_controller.rb
class UserPageController < ApplicationController
  before_action :set_archives
  before_action :set_populars

  def set_archives
    # TODO: 月ごとに集計する
    @archives = Post.count_per_month
  end

  def set_populars
    # TODO: よく読まれている記事を抜粋する
    @populars = []
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
        site: "takaaa220 Tech Blog",
        title: "takaaa220 Tech Blog",
        description: "渋谷のベンチャー企業でバックエンドもフロントエンドも粛々と書いているエンジニアの個人ブログ．主にサーバはRuby，フロントはReactを書いています．",
        keywords: "rails,ruby,react,バックエンド,フロントエンド",
        icon: [
            { href: image_tag("/favicon_32.ico") },
            { href: image_tag("/favicon.ico") },
            { href: image_tag("/takaaa220.png"), rel: 'apple-touch-icon', sizes: '180x180',type: 'image/png' }
        ],
        noindex: !Rails.env.production?,
        canonical: request.original_url,
        charset: 'UTF-8',
        og: {
            title: :title,
            description: :description,
            type: "website",
            url: request.original_url,
            image: image_tag("/takaaa220.png"),
            site_name: "Engineer.new(name: 'takaaa220')",
            locale: "ja_JP"
        },
        twitter: {
            site: "@takaaa220",
            card: "summary",
            image: image_tag("/takaaa220.png")
        }
    }
  end
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  require "redcarpet"
  require "coderay"

  class HTMLWithCoderay < Redcarpet::Render::HTML
    def block_code(code, language)
      language = language.split(':')[0]

      case language.to_s
      when 'rb'
        lang = 'ruby'
      when 'yml'
        lang = 'yaml'
      when 'css'
        lang = 'css'
      when 'html'
        lang = 'html'
      when ''
        lang = 'md'
      else
        lang = language
      end

      CodeRay.scan(code, lang).div
    end
  end

  def markdown(text)
    html_render = HTMLWithCoderay.new(filter_html: true, hard_wrap: true)
    options = {
      autolink: true,
      space_after_headers: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      tables: true,
      hard_wrap: true,
      xhtml: true,
      lax_html_blocks: true,
      strikethrough: true
    }
    markdown = Redcarpet::Markdown.new(html_render, options)
    markdown.render(text)
  end
end

app/views/admin/posts/_form.html.slim
= form_with model: post, url: url, local: true, method: method, class: "AdminForm", id: "editor" do |f|
  .AdminForm__Item
    = f.label :title, class: "AdminForm__Label"
    = f.text_field :title, class: "AdminForm__TextBox"

  .AdminForm__Item
    = f.label :description, class: "AdminForm__Label"
    = f.text_area :description, class: "AdminForm__TextArea -small"

  .AdminForm__Item
    = f.label :tag_ids, class: "AdminForm__Label"
    = f.collection_check_boxes :tag_ids, Tag.all, :id, :name do |check|
      = check.check_box
      = check.label

  .AdminForm__Item.-flex
    .AdminForm__Content
      = f.label :content, class: "AdminForm__Label"
      = f.text_area :content, class: "AdminForm__TextArea", "v-model": "input"
    .AdminForm__Content
      .Post__Markdown v-html='input | marked'

  = f.submit "送信", class: "Button"




  - content_for(:javascript) do
    javascript:
      window.onload = function() {
        new Vue({
          el: '#editor',
            data: {
              input: '<%== j post.content %>',
            },
            filters: {
              marked: marked,
            },
          });
        };

app/views/admin/posts/_post.html.slim
tr.AdminPosts__Item
  td
    = post.title
  td
    = post.description.truncate(40)
  td
    = link_to "編集", edit_admin_post_path(post.pid)
    br
    = link_to "見た目チェック", admin_post_path(post.pid)
    = post.toggle_button

app/views/admin/posts/edit.html.slim
.Container
  .Container__Main
    = render "form", post: @post, url: admin_post_path(@post.pid), method: :patch

app/views/admin/posts/index.html.slim
.AdminPosts
  table
    thead
      tr.AdminPosts__Item
        th
          | タイトル
        th
          | 概要
        th
          | ステータス

    = render @posts

app/views/admin/posts/new.html.slim
.Container
  .Container__Main
    = render "form", post: @post, url: admin_posts_path, method: :post

app/views/admin/posts/show.html.slim
.Container
  .Container__Main
    .Post
      p.Post__Date
        = @post.published_time

      h1.Post__Title
        = @post.title

      .mb4.Tag
        - @post.tags.pluck(:name).each do |tag|
          .Tag__Item
            = tag

      div.Post__Markdown
        = markdown(@post.content).html_safe

app/views/admin/tags/_tag.html.slim
tr.AdminPosts
  td
    = tag.name
  td
    = button_to "削除", admin_tag_path(tag), method: :delete, data: { confirm: "削除しますか？" }

app/views/admin/tags/index.html.slim
.mb8
  = form_with(model: @tag, url: admin_tags_path, method: :post, class: "AdminForm", local: true) do |f|
    = f.label :name, class: "AdminForm__Label"
    .AdminForm__Item.-flex
      = f.text_field :name, class: "AdminForm__TextBox mr8"
      = f.submit "作成", class: "Button"
.AdminPosts
  table
    thead
      tr.AdminPosts__Item
        th
          | タグ名
        th
          | ボタン
    = render @tags

app/views/layouts/_footer.html.slim
footer.Footer
  p.Footer__CopyRight
    | (C) 2019 Takashi Hirata

app/views/layouts/_header.html.slim
header.Header
  a.Header__Link href="/"
    | takaaa220's Engineer Blog
  p.Header__Description
    | 技術系の記事を投稿していきます．
  - if admin_login?
    nav
      ul.Nav
        li.Nav__Item
          = link_to "記事一覧", admin_posts_path
        li.Nav__Item
          = link_to "タグ一覧", admin_tags_path
        li.Nav__Item
          = link_to "新規作成", new_admin_post_path
        li.Nav__Item
          = button_to "ログアウト", logout_path, method: :delete
  - else
    nav
      ul.Nav
        li.Nav__Item
          = link_to "Githubへ", "https://github.com/takaaa220", target: "_blank", rel: "noopener"
        li.Nav__Item
          = link_to "Twitterへ", "https://twitter.com/takaaa220", target: "_blank", rel: "noopener"
  / TODO: 検索窓設置

app/views/layouts/_meta.html.slim
= display_meta_tags(default_meta_tags)

app/views/layouts/_user_page.html.slim
main.Main
  = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    = csrf_meta_tags
    = csp_meta_tag
    = render "layouts/meta"
    = stylesheet_link_tag    'application', media: 'all'
    = stylesheet_pack_tag 'application'
    = javascript_include_tag 'application'
    meta name="viewport" content="width=device-width,initial-scale=1"
    link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700&display=swap" rel="stylesheet"
    link href="https://fonts.googleapis.com/css?family=Roboto:400,700&display=swap" rel="stylesheet"
    script src='https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.10/vue.js'
    script src='https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.js'

  body
    == breadcrumbs separator: " &rsaquo; "
    = button_to "ログアウト", logout_path, method: :delete if admin_login?
    = render "layouts/header"
    = yield
    = render "layouts/footer"
    = javascript_pack_tag "application"
    = yield(:javascript)

app/views/layouts/side_menus/_archive.html.slim
section.Archive
  h4.SideMenu__Title
    | 過去の記事
  ul.Archive__Items
    - @archives.each do |date, count|
      li.Archive__Item
        = link_to posts_path(date: date) do
          = date
          br
          = count

app/views/layouts/side_menus/_index.html.slim
= render "layouts/side_menus/profile"
= render "layouts/side_menus/archive"
= render "layouts/side_menus/popular"

app/views/layouts/side_menus/_popular.html.slim
section.Popular
  h4.SideMenu__Title
    | よく読まれている記事
  ul.Popular__Items
    - @populars.each do |popular|
      li.Popular__Item
        = popular

app/views/layouts/side_menus/_profile.html.slim
section.Profile
  h4.SideMenu__Title
    | 自己紹介
  .Profile__ImgWrapper
    = image_tag "/takaaa220.png", alt: "takaaa220", class: "Profile__Img"
    .Profile__SNSs
      a.Profile__SNS href="https://github.com/takaaa220" target="_blank"
        | Github
      a.Profile__SNS href="https://twitter.com/takaaa220" target="_blank"
        | Twitter
  h5.Profile__Name
    | Takashi Hirata(@takaaa220)
  p.Profile__Description
    | 1996年生まれ．渋谷のベンチャー企業で働いています．バックエンドの方が好きですが，フロントも書きます．
    br
    | 基本的にはRubyとReactを書いてますが，Python，Go，Vueとかも一応書けます（あんまり好きじゃない）
    br
    | これと言って趣味がないので，休日もコードを書いてます．

app/views/posts/_post.html.slim
li.Posts__Item
  .Post
    p.Post__Date
      = post.published_time

    h2.Post__Title
      = link_to post.title, post_path(post.pid), class: "Post__Link"

    ul.mb4.Tag
      - post.tags.pluck(:name).each do |tag|
        li.Tag__Item
          = tag
    div.Post__Markdown
      = markdown(post.content).html_safe

app/views/posts/index.html.slim
- set_meta_tags title: "新着記事一覧"

- breadcrumb :posts

= render "layouts/user_page" do
  ul.Posts
    = render @posts

  .mb8
    = paginate @posts

app/views/posts/show.html.slim
- set_meta_tags title: @post.title, description: @post.description

- breadcrumb :post, @post

= render "layouts/user_page" do
  .Post
    p.Post__Date
      = @post.published_time

    h1.Post__Title
      = @post.title

    ul.mb4.Tag
      - @post.tags.pluck(:name).each do |tag|
        li.Tag__Item
          = tag

    div.Post__Markdown
      = markdown(@post.content).html_safe